name: Get Secret

on:
  push:
    branches:
      - main

jobs:
  get-secret-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "SECRET_API_KEY=${{ secrets.DEMO_SECRET }}" >> $GITHUB_ENV
